import { z } from 'zod';

enum TASK_STATUS {
  TODO = "TODO",
  IN_PROGRESS = "IN_PROGRESS",
  DONE = "DONE"
}

export const TaskStatus = z.nativeEnum(TASK_STATUS);

enum TASK_PRIORITY {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH"
}

export const TaskPriority = z.nativeEnum(TASK_PRIORITY);

export const TaskSchema = z.object({
  id: z.number().optional(), // ID is optional because it's auto-generated by the database
  title: z.string()
    .max(100, { message: "Title must be less than 100 characters."}),
  description: z.string(),
  status: TaskStatus,
  priority: TaskPriority
});
